name: Upload artifacts

on: 
  release:
    types:
      - created
jobs:

  artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        
      - name: Artifacts
        run: docker run -v $(pwd):/home/dev -w /home/dev golang:1.16 make artifacts VERSION=${{ github.event.release.tag_name }}

      - name: darwin amd64 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/darwin-amd64-ec2ti.tar.gz
          asset_name: darwin-amd64-ec2ti.tar.gz
          asset_content_type: application/gzip

      - name: darwin arm64 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/darwin-arm64-ec2ti.tar.gz
          asset_name: darwin-arm64-ec2ti.tar.gz
          asset_content_type: application/gzip

      - name: linux 386 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/linux-386-ec2ti.tar.gz
          asset_name: linux-386-ec2ti.tar.gz
          asset_content_type: application/gzip

      - name: linux amd64 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/linux-amd64-ec2ti.tar.gz
          asset_name: linux-amd64-ec2ti.tar.gz
          asset_content_type: application/gzip

      - name: linux ppc64 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/linux-ppc64-ec2ti.tar.gz
          asset_name: linux-ppc64-ec2ti.tar.gz
          asset_content_type: application/gzip

      - name: linux ppc64le
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/linux-ppc64le-ec2ti.tar.gz
          asset_name: linux-ppc64le-ec2ti.tar.gz
          asset_content_type: application/gzip

      - name: windows 386 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/windows-amd64-ec2ti.tar.gz
          asset_name: windows-386-ec2ti.tar.gz
          asset_content_type: application/gzip

      - name: windows amd64 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/windows-amd64-ec2ti.tar.gz
          asset_name: windows-amd64-ec2ti.tar.gz
          asset_content_type: application/gzip
