name: Upload artifacts

on: 
  release:
    types:
      - created
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        
      - name: Artifacts
        run: make artifacts 

      - name: upload bundled
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./built/darwin-amd64-ec2ti.tar.gz
          asset_name: darwin-amd64-ec2ti.tar.gz
          asset_content_type: application/gzip
